carusele/urls.py
from django.conf.urls import url

from carusele import views
from carusele import models

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^art/$', views.articles, name='articles'),
    url(r'^art/(?P<id>[0-9]+)/$', views.article, name='article'),
]

untitled1/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.contrib.auth.models import User
import admin_tools.urls
from django.conf import settings

from rest_framework import routers, serializers, viewsets

from carusele import urls as carusele_urls
from teamlogic import urls as teamlogic_urls
from ADFS.api import urls as common_api_urls
from ADFS import views


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include(admin_tools.urls)),
    url(r'^permissions/', views.user_permissions),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'logic/', include(teamlogic_urls)),
    url(r'^login/github', views.autorisation_github),
    url(r'^login/', views.autorisation),
    url(r'^register/', views.register),
    url(r'^survey', views.survey),
    url(r'^reglament/', views.reglament),
    url(r'^register_attention/', views.register_attention),
    url(r'^attention/(?P<id>[0-9]+)/', views.view_attention,
        name='attention'),
    url(r'^', include(carusele_urls)),
    url(r'^common/', include(common_api_urls.api_patterns)),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url('^', include('django.contrib.auth.urls')),
)

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teamlogic/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

from datetime import datetime
from itertools import groupby

from utils.helpers import NULLABLE, cmp_to_key

from .api.helpers import parse_time_to_string


class Stadium(models.Model):
    """
    Simple model of stadium.
    """
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    accr = models.BooleanField(default=True)
    description = models.TextField(default="olo")
    estimate = models.FloatField()
    physics = models.IntegerField()
    # Need to add relation to Date and Time free!!!
    home = models.ManyToManyField('Team', **NULLABLE)
    image = models.ImageField(upload_to='./stadions', default='./404/stadion.jpg', **NULLABLE)

    class Meta:
        verbose_name = "Стадион"
        verbose_name_plural = "Стадионы"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stadion", args=(self.id,))


class TimeBoard(models.Model):
    date = models.DateField()
    time1 = models.IntegerField()
    time2 = models.IntegerField()
    match = models.ForeignKey('Match', **NULLABLE)
    stadion = models.ForeignKey('Stadium')

    def __str__(self):
        return '%s / %s [%s - %s]' % (str(self.match), self.stadion.name,
                                      parse_time_to_string(self.time1),
                                      parse_time_to_string(self.time2))


class Player (models.Model):
    """
    Simple model of player.
    """
    firstName = models.CharField(max_length=70)
    lastName = models.CharField(max_length=70)
    birth = models.DateField()
    vk_link = models.CharField(max_length=30, null=True)
    # G - goalkeeper, H - defender, F - nap
    basePosition = models.CharField(max_length=1)
    image = models.ImageField(upload_to="./players",
                              default="./404/profile.jpg", **NULLABLE)
    history = models.ManyToManyField('Team', through='RecOfTeam')

    class Meta:
        verbose_name = "Игрок"
        verbose_name_plural = "Игроки"

    def __str__(self):
        return "%s %s" % (self.firstName, self.lastName)
    
    def __unicode__(self):
        return unicode(self.__str__())

    def __unicode__(self):
        return unicode(self.__str__())

    def get_absolute_url(self):
        return reverse("player", args=(self.id,))


class Team(models.Model):
    """
    Simple model of Team.
    """
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    foundation = models.IntegerField()
    image = models.ImageField(upload_to="./teams",
                              default="./404/team.jpg", **NULLABLE)

    players = models.ManyToManyField('Player', through='RecOfTeam')
    vk_link = models.CharField(max_length=30, default="nulls", **NULLABLE)
    captain = models.ForeignKey('Player', related_name='+', **NULLABLE)
    home = models.ForeignKey('Stadium', **NULLABLE)

    def get_current_players(self):
        return RecOfTeam.objects.filter(team=self, endDate__gte=timezone.now())

    class Meta:
        verbose_name = "Команда"
        verbose_name_plural = "Команды"

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name

    def __unicode__(self):
        return unicode(self.__str__())

    def get_absolute_url(self):
        return reverse("team", args=(self.id,))


class RecOfTeam(models.Model):
    """
    All players can exchange teams times for times.
    We need to store this information. Also in every
    team Player has individual number.
    """
    beginDate = models.DateField(**NULLABLE)
    endDate = models.DateField(**NULLABLE)
    team = models.ForeignKey('Team')
    player = models.ForeignKey('Player')
    number = models.IntegerField(default=-1)
    isActive = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Игрок в команде"
        verbose_name_plural = "Игроки в командах"

    def __unicode__(self):
        return unicode("%s (%s)" % (self.player.__unicode__(),
                                    self.team.__unicode__()))
    
    def __str__(self):
        return "%s (%s)" % (self.player, self.team)

    def get_end_date(self):
        if self.endDate.year > datetime.now().year:
            return u"At our time"
        else:
            return self.endDate


class Goal(models.Model):
    """
    Model of goal. Goal has accordings author,
    team of author, type (penalty, no-penalty),
    minuts of match.
    """
    author = models.ForeignKey(Player)
    team = models.ForeignKey(Team, **NULLABLE)
    type = models.CharField(max_length=2)
    min = models.IntegerField(null=True)

    class Meta:
        verbose_name = "Гол"
        verbose_name_plural = "Голы"

    def __unicode__(self):
        return "Goal of %s" % self.author.__unicode__()


class Match(models.Model):
    """
    Simple model of match.
    """
    league = models.ForeignKey('Tournament', default=1, null=True)
    home = models.ForeignKey(Team, related_name='+')
    away = models.ForeignKey(Team, related_name='+')
    home_goal = models.IntegerField(default=0)
    away_goal = models.IntegerField(default=0)
    home_goal_first = models.IntegerField(**NULLABLE)
    away_goal_first = models.IntegerField(**NULLABLE)
    technical = models.BooleanField(default=False)
    place = models.ForeignKey(Stadium, **NULLABLE)
    date_time = models.DateTimeField(**NULLABLE)
    home_goals = models.ManyToManyField('Goal',
                                        related_name='home', **NULLABLE)

    away_goals = models.ManyToManyField('Goal',
                                        related_name='away', **NULLABLE)

    hasResult = models.BooleanField(default=False)
    status = models.CharField(max_length=30, **NULLABLE)
    register = models.BooleanField(default=False)

    tour = models.IntegerField(**NULLABLE)

    locked = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Матч"
        verbose_name_plural = "Матчи"

    def this_team(self, team):
        """ Has team take competition in Match? """
        return team in (self.home, self.away)

    def all_team_matches(self, team):
        a = Match.objects.all()
        x = []
        for i in a:
            if i.this_team(team):
                x.append(i)
        return x

    def is_starts(self):
        c = self.date_time - timezone.now()
        c = int(c.total_seconds())
        if c > 4000:
            return -1  # Don't beginn's
        elif c < 0:
            return 1  # HAS a result
        else:
            return 0  # Online

    def ago(self):
        c = self.date_time - timezone.now()
        c = int(c.total_seconds())
        return c/60

    def is_home_winner(self):
        return self.home_goal > self.away_goal

    def is_away_winner(self):
        return self.away_goal > self.home_goal

    def is_drawn(self):
        return self.home_goal == self.away_goal

    def get_absolute_url(self):
        return reverse("match", args=(self.id,))

    def getWinner(self):
        if self.is_home_winner():
            return self.home
        if self.is_away_winner():
            return self.away

        return None

    def get_result_of_team(self, team):
        winner = self.getWinner()
        if winner is None:
            return 'drawn'
        if winner.pk == team.pk:
            return 'win'
        return 'lose'

    def thisTeamIsWinner(self, team):
        winner = self.getWinner()
        if winner is None:
            return False

        if winner == team.pk:
            return True

        return False

    def __str__(self):
        if not self.hasResult:
            return "%s - %s" % (self.home.name, self.away.name)
        return "%s - %s (%i - %i)" % (self.home.name, self.away.name,
                                              self.home_goal, self.away_goal)

    def __unicode__(self):
        return unicode(self.__str__())


class Tournament(models.Model):
    """
    Simple model of football league. If leagues of this type
    there is minimum one match between any two teams from league.
    """
    name = models.CharField(max_length=30)
    begin_date = models.DateField()
    end_date = models.DateField()
    image = models.ImageField(default="./404/tournament.jpg", **NULLABLE)
    #And so hard!
    members = models.ManyToManyField(Team, through='TeamInLeague')
    members2 = models.ManyToManyField(Team,
        related_name='members2', **NULLABLE)

    matchs = models.ManyToManyField('MatchInLeague')

    class Meta:
        verbose_name = "Чемпионат"
        verbose_name_plural = "Чемпионаты"

    def get_calendar(self):
        """
        It's good idea to have calendar of matches in
        dictinary format with keys are number of tours
        anv values is sets of matches.
        """
        matchs = MatchInLeague.objects.filter(league_id=self.id)
        tour_count = max([match.tour for match in matchs])
        for tour in range(1, tour_count + 1):
            yield (tour, matchs.filter(tour=tour))

    def generate_calendar(self):
        """
        If admin of ADFS will create new tournament he just
        must run this method for generate list of matches
        automatically.
        """
        pass  # not Implemented

    def teams_iter(self):
        lst_teams = list(self.teaminleague_set.all())

        # Comparator.
        def a(x, y):
            x, y = x.get_points(), y.get_points()
            if x > y:
                return 1
            if x == y:
                return 0
            if x < y:
                return -1

        lst_teams.sort(key=cmp_to_key(a), reverse=True)
        return lst_teams

    def __str__(self):
        return "%s %s" % (self.name, self.get_season())

    def get_season(self):
        a = self.begin_date.year
        b = self.end_date.year
        if a == b:

templates/article.html
{% extends "base.html" %}

{% block content %}
    <h1> {{ article.title }}</h1>


    <small> Опубликовано: {{ article.pubdate }}</small>
    <br>
    <small>{{ article.description }}</small>
    <br>
    <div class="article-content">
      <p> {{ article.content|safe }}</p>
    </div>
    <br>

    <div class="btn-group">
        <button class="btn">
            <script language="JavaScript"> document.write({{ number }} -2) </script>
        </button>
        <button class="btn">
            <script language="JavaScript"> document.write({{ number }} -1) </script>
        </button>
        <button class="btn"><strong> {{ number }} </strong></button>
        <button class="btn">
            <script language="JavaScript"> document.write({{ number }} +1) </script>
        </button>
        <button class="btn">
            <script language="JavaScript"> document.write({{ number }} +2) </script>
        </button>
    </div>
{% endblock %}

templates/articles.html
{% extends "base.html" %}

{% block content %}
  <div class="articles">
    {% for article in articles %}
      <div class="articles-item">
        <h3><a href="{{article.get_absolute_url}}">{{article.title}}</a></h3>
        <span>{{article.pubdate}}</span>
        <div class="articles-item__description">
          {{article.description}}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/attention.html
{% extends "base.html" %}

{% block content %}
    <h2> Регистрация заявки на участие в первой лиге АДФС </h2>
    <form role="form" method="post">
        {% csrf_token %}
        {% load bootstrap %}
        <label> Ответьте, пожалуйста, на несколько простых вопросов и ваша заявка обязательно будет рассмотрена администрацией! </label>

        <div class="form-group" id="person">

                <div class="form-group">

                    {{ form.name | bootstrap }}

                    {{ form.vkLink | bootstrap }}

                    {{ form.phone | bootstrap }}

                    {{ form.team | bootstrap }}

                </div>
                <div class="form-group" id="tournaments">
                    <p> Подать заявку на следующие турниры: </p>

                    <div class="checkbox" id="first_league">
                        {{ form.first_league | bootstrap }}
                    </div>

                    <div class="checkbox" id="pokal">
                        {{ form.pokal | bootstrap }}
                    </div>

                    <div class="checkbox" id="winter_pokal">
                        {{ form.winter_pokal |bootstrap }}
                    </div>
                </div>

                <button type="submit" class="btn btn-success">Заявиться</button>
        </div>
    </form>
{% endblock %}

templates/attention_view.html
{% extends "base.html" %}

{% block content %}
    <h2> Заявка на участие в АДФС </h2>

<b>Заявку подал: <br></b>
{{ attention.name }} <br>
<b>Название команды: <br></b>
{{ attention.team }} <br>
{% endblock %}

templates/attentions.html
{% extends "base.html" %}

{% block content %}

   Спасибо за заявку! Мы свяжемся с Вами в ближайшее время!

    <h3> Ваша заявка: </h3>
    <strong> Представитель:</strong> {{ attentions.name }} <br>
    <strong> Команда: </strong> {{ attentions.team }} <br>
    <br>

    <h3> Вы заявились на следующие турниры: </h3>
    {% if attentions.first_league %}
            <li> Первая лига АДФС 2016 </li>
    {% endif %}

    {% if attentions.pokal %}
            <li> Кубок АДФС 2016 </li>
    {% endif %}

    {% if attentions.winter_pokal %}
            <li> Зимний кубок АДФС 2015/16 </li>
    {% endif %}

{% endblock %}

templates/autorisation.html
<div class="auth-panel">
  <ul class="breadcrumb">
    <li><a href="#"> Авторизация </a> <span class="divider"></span></li>
  </ul>
  <div id="login-app" {% if user.is_authenticated %}data-auth="true" data-username="{{user.username}}"{% endif %}>
  {% if user.is_authenticated %}
    Вы авторизованы как <strong><a href="{% url 'django.contrib.auth.views.login' %}">{{user.username}}</a></strong>
    <div class="col-sm-12">
      {% csrf_token %}
      <button class="btn btn-default" style="margin-top:20px;" id="logOut">
        Выйти
      </button>
    </div>
  {% else %}
  <form class="form-horizontal" id="login-form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}
    <div class="form-group">
      <label> Логин: </label>
      <input class="form-control" name="login" type="text" placeholder="Император">
    </div>
    <div class="form-group">
      <label> Пароль: </label>
        <input class="form-control" name="password" type="password" placeholder="Космонавтика">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Войти</button>
        <button id="register" class="btn btn-default" data-toggle="modal" data-target="#modalRegister">Регистрация</button>
    </div>
  </form>
  <!-- Modal -->
<div id="modalRegister" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Регистрация нового пользователя</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" id="register-form">
          <div class="row">
            <div class="col-sm-6">
              <h3>Выберите аватар</h3>
            <img src="#" class="img" style="width: 220px; height: 220px; border-radius: 8px;" id="avatarpreview"></img>
            <div class="btn-group">
            <button class="btn btn-default" id="avatarBtn">Загрузить</button>
          </div>
            </div>
            <div class="col-sm-6" style="border-left: solid 1px; border-color: #999999;">
                <div class="form-group col-sm-12">
                  {% csrf_token %}
                  <label for="login">Логин
                    <input class="form-control" type="text" name="login" id="login">
                  </label>
                </div>
                <div class="form-group col-sm-12">
                  <label for="password">Пароль
                    <input class="form-control" type="password" name="password" id="password">
                  </label>
                </div>
                <div class="form-group col-sm-12">
                  <label for="password2">Повторите пароль
                    <input class="form-control" type="password" name="password2" id="password2">
                  </label>
                </div>
                <div class="form-group col-sm-12">
                  <label for="email">Электронная почта
                    <input class="form-control" type="email" name="email" id="email">
                  </label>
                </div>
                <input type="file" name="avatar" id="avatarupl" style="display:none;">
            </div>

        </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="btn-register">Регистрация</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
      </div>
      <script>
        $('#register').on('click', (event) => event.preventDefault());
        $('#avatarBtn').on('click', (event) => {
          event.preventDefault();
          $('#avatarupl').trigger('click');
        });

        $('#btn-register').on('click', (event) => {
          var data = $('#register-form').serializeArray();
          $.ajax({
            type: "POST",
            url: '/register/',
            data: {login: data[1].value,
                   password: data[2].value,
                   email: data[4].value,
                   csrfmiddlewaretoken: data[0].value,
            },
            statusCode: {
              201: () => {
                console.log('sycc');
                $.ajax({
                  type: "POST",
                  url: '/login/',
                  data: {
                    login: data[1].value,
                    password: data[2].value,
                  },
                  success: location.reload
                });
              },
            },
            error: (data) => {
              console.log('error by login!');
              console.log(data.responseText);
            },
            dataType: 'application/json',
        });
        });

        var openFile = function(event) {
        var input = event.target;

        var reader = new FileReader();
        reader.onload = function(){
          var dataURL = reader.result;
          var output = document.getElementById('avatarpreview');
          output.src = dataURL;
        };
        reader.readAsDataURL(input.files[0]);
      };
      $('#avatarupl').on('change', openFile);
      </script>
    </div>

  </div>
</div>
  {% endif %}
  </div>
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="shortcut icon" href="{% static 'ball.png' %}" type="image/png">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src='{% static "bundles/main.js" %}'></script>
    <script src="https://d3js.org/d3.v4.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/antd/2.13.9/antd.css" rel="stylesheet">
    <meta name="google-site-verification" content="VNfiMoaoZOHJu0sVM6Q76JDicuFwen4JOaYotfUhlUo" />
    <meta name="yandex-verification" content="b55474fe8e01ccee" />
    <meta charset="utf-8">
    <link rel="styleheet" href="{% static "css/skin.css" %}">
    <link href="{% static "bundles/styles.css" %}" rel="stylesheet">
    {% block custom_css %} {% endblock %}
    {% block custom_js %} {% endblock %}
    <style type="text/css">
        #centere {
            background-image: none;
            background-color: #D8D8D8;

        }

        #headpan {
            background-color: black;
        }

        #centere:hover {
            background-color: #C6CAE1;
        }

        #carousel-136312 {
            width: 100%;
            max-height: 600px;
        }

        .carousel-inner > .item > img,
        .carousel-inner > .item > a > img {
            overflow: hidden;
            width: 100%;
            max-height: 600px;
            margin: auto;
        }

        .titleref {
            color: bisque;
        }
    </style>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Ассоциация дворового футбола Саратова - 2017!</title>

    <meta name="description" content="портал АДФС">
    <meta name="keywords" content="футбол, ассоциация, дворовый, чемпионат, саратов" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

</head>

<body>
  <div class="loader-line"></div>
  {% include "menu.html" %}
  <div class="container-fluid">
      <div class="row-fluid">
          <div class="col-lg-10 col-md-9 col-xs-12 black text-left" id="root2"> {% block content %} {% endblock %} </div>
          <div class="col-lg-2 col-md-3 col-xs-12 grey text-center"> {% block autoris %}{% include "autorisation.html" %}{% endblock %} </div>
      </div>
  </div>
</body>
</html>

templates/for_admin.html
{% include 'base.html' %}

{% block 'content' %}

    <ul class="breadcrump">
        <li><a href="">Администратору АДФС</a></li>
    </ul>



{% endblock %}

templates/gratulations.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}

{% block custom_css %}
  <link href="{% static "css/server-error.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h2> Добро пожаловать на официальный портал АДФС, уважаемый {{ user.username }}!</h2>
    <div class="col-md-12">
      <div class="row profile__container">
        <div class="profile__container-avatar">
          {% thumbnail user.avatar "256x256" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="media-object" float="left">
          {% endthumbnail %}
        </div>
        <div class="profile__container-form" id="root2">
          УРАШКЧКИ!
        </div>
      </div>
    </div>
  {% else %}
    <h2> Неверное имя пользователя или пароль. Попробуйте ещё раз! </h2>
    <div class="profile__container">
      <div class="col-md-12 wrong-login">
        <image src="/media/404/wrong-login.jpg">
      </div>
    </div>
  {% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block content %}
    <div class="carousel slide" id="carousel-136312">
        <ol class="carousel-indicators">
            <li data-slide-to="0" data-target="#carousel-136312"></li>
            <li data-slide-to="1" data-target="#carousel-136312" class="active"></li>
            <li data-slide-to="2" data-target="#carousel-136312"></li>
        </ol>
        <div class="carousel-inner">
            {% for Elems in Elements|slice:"1" %}
                <div class="item active">
                    <img alt="Carousel Bootstrap Second" src="{{ Elems.image.url }}">

                    <div class="carousel-caption">
                        <h4>{{ Elems.description }}</h4>
                        <a href="{{ Elems.caruse.get_absolute_url }}" class="titleref"> {{ Elems.content }}</a>
                    </div>
                </div>
            {%  endfor %}

            {% for Elems in Elements %}
                <div class="item">
                    <img class="img-rounded" alt="Carousel Bootstrap Third" src="{{ Elems.image.url }}">
                    <div class="carousel-caption">
                        <a href="{{ Elems.news.get_absolute_url }}" class="titleref"> <h4> {{ Elems.description }} </h4></a>
                    </div>
                </div>
            {% endfor %}
        </div>

        <a class="left carousel-control" href="#carousel-136312" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-136312" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <h1> Наши поздравлялики! </h1>
    Вы авторизованы, уважаемый {{ login }}

{% endblock %}

templates/player.html
{% extends "base.html" %}

{% block content %}

    <style type="text/css">
        img {
            float:left;
            height: auto;
            width: 200px;
        }
        #info {
            position: relative;
            left: 5px;
        }
    </style>

        <ul class="breadcrumb">
        <li><a href="#"> АДФС </a> <span class="divider"></span></li>
        <li><a href="#"> Игроки </a> <span class="divider"></span></li>
        <li><a href="#"> {{ player.firstName }}  {{ player.lastName }}  </a> <span class="divider"></span></li>
    </ul>


    <h1> {{ player.firstName }}  {{ player.lastName }}  </h1>


    <img src="{{ player.image.url }}" class="img-polaroid" float="left">


    <div id="info">
    <strong>  Родился: </strong> {{ player.birth }}
    <br>
    <strong>  Профиль в вк: </strong> <a href="vk.com/"{{ player.vkLink }}> {{ player.vkLink }} </a>
    <br>
    <strong>  Игровая позиция:</strong>
    {% if player.basePosition == 'G' %}
        <span class="badge badge-warning">GK</span>  вратарь
    {% endif %}

    {% if player.basePosition == 'H' %}
        <span class="badge badge-warning">DF</span> защитник
    {% endif %}
    {% if player.basePosition == 'F' %}
        <span class="badge badge-warning">FRW</span> нападающий
    {% endif %}
    <br>

    <br>
    <table class="table table-striped">
        <caption> <strong> История выступлений: </strong></caption>
        <thead>
        <tr>
            <th>Команда</th>
            <th>Дата подписания:</th>
            <th>Дата отзаявки:</th>
        </tr>
        </thead>
        <tbody>
        {% for foo in player.recofteam_set.all %}
            <tr>
                <td> <a href = '{{ foo.team.get_absolute_url}}'>{{ foo.team }}</a> </td>
                <td> {{ foo.beginDate }}</td>
                <td> {{ foo.get_end_date }}</td>
            </tr>
        {% endfor %}
        
        </tbody>
    </table>
    </div>

{% endblock %}